AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance Build Template

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0 # Example AMI ID (use an appropriate one for your region)
      KeyName: your-key-pair-name  # Replace with your actual EC2 Key Pair name
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: MyEC2Instance

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Enable SSH and HTTP access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0   # Allow SSH access from anywhere (use with caution)
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0   # Allow HTTP access from anywhere

Outputs:
  EC2InstancePublicIP:
    Description: "Public IP of the newly created EC2 instance"
    Value: !GetAtt EC2Instance.PublicIp
